M48
; DRILL file {KiCad 9.0.3} date 2026-09-12T01:27:39-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-12T01:27:39-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X6.68Y-15.0
X6.68Y-20.78
T2
X4.0Y-9.75
X4.0Y-32.25
X40.0Y-39.25
X49.25Y-2.75
M30
